import type { PixeerAppContext } from 'pixeer';

/**
 * Renders the PixeerAppContext as a TypeScript module that can be committed to
 * the repo and imported directly — no runtime analysis needed.
 */
export function generateContextModule(appContext: PixeerAppContext): string {
  const json = JSON.stringify(appContext, null, 2);
  return [
    '// AUTO-GENERATED by @pixeer/analyzer — do not edit manually',
    "// Re-run `pixeer-analyze` (or let the Vite plugin handle it) to regenerate.",
    '',
    "import type { PixeerAppContext } from 'pixeer';",
    '',
    `export const pixeerAppContext = ${json} satisfies PixeerAppContext;`,
    '',
  ].join('\n');
}
